
DROP PROCEDURE IF EXISTS `Apq_CreateNewTable`;

DELIMITER $$
CREATE PROCEDURE `Apq_CreateNewTable`(
	pTID	INT
)
BEGIN
	DECLARE minCID INT;
	DECLARE nCID INT;
	DECLARE maxCID INT;
	
	DECLARE vSchemaName VARCHAR(192);
	DECLARE vTableName VARCHAR(192);
	DECLARE vENGINE VARCHAR(192);
	DECLARE vCREATE_OPTIONS VARCHAR(765);
	DECLARE vTABLE_COMMENT VARCHAR(240);
	DECLARE vPrimaryKeys TEXT;
	
	DECLARE vColName VARCHAR(192);
	DECLARE vDefaultValue LONGTEXT;
	DECLARE vNullAble TINYINT;
	DECLARE vDATA_TYPE VARCHAR(192);
	DECLARE vCHARACTER_MAXIMUM_LENGTH BIGINT;
	DECLARE vCHARACTER_OCTET_LENGTH BIGINT;
	DECLARE vNUMERIC_PRECISION BIGINT;
	DECLARE vNUMERIC_SCALE BIGINT;
	DECLARE vCHARACTER_SET_NAME VARCHAR(192);
	DECLARE vCOLLATION_NAME VARCHAR(192);
	DECLARE vCOLUMN_TYPE LONGTEXT;
	DECLARE vCOLUMN_KEY VARCHAR(3);
	DECLARE vis_auto_increment TINYINT;
	DECLARE vCOLUMN_COMMENT VARCHAR(1024);
	
	SELECT SchemaName, TableName, `ENGINE`, CREATE_OPTIONS, TABLE_COMMENT, PrimaryKeys
	  INTO vSchemaName,vTableName,vENGINE,vCREATE_OPTIONS,vTABLE_COMMENT,vPrimaryKeys
	  FROM dbv_table
	 WHERE TID = pTID;
	
	SET @STMT = CONCAT('CREATE TABLE IF NOT EXISTS `',vTableName,'`(
');
	 
	SELECT IFNULL(MIN(CID),0), IFNULL(MAX(CID),-1)
	  INTO minCID, maxCID
	  FROM dbv_column
	 WHERE TID = pTID;
	
	SET nCID = minCID;
	WHILE nCID <= maxCID DO
		SELECT  ColName, DefaultValue, NullAble, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE,
			 CHARACTER_SET_NAME, COLLATION_NAME, COLUMN_TYPE, COLUMN_KEY, is_auto_increment, COLUMN_COMMENT
		  INTO vColName,vDefaultValue,vNullAble,vDATA_TYPE,vCHARACTER_MAXIMUM_LENGTH,vCHARACTER_OCTET_LENGTH,vNUMERIC_PRECISION,vNUMERIC_SCALE,
			vCHARACTER_SET_NAME,vCOLLATION_NAME,vCOLUMN_TYPE,vCOLUMN_KEY,vis_auto_increment,vCOLUMN_COMMENT
		  FROM dbv_column
		 WHERE TID = pTID AND CID = nCID;
		IF FOUND_ROWS() > 0 THEN
			SET @STMT = CONCAT(@STMT,'	`',vColName,'` ',vCOLUMN_TYPE);
			
			IF vNullAble = 0 THEN
				SET @STMT = CONCAT(@STMT,' NOT NULL');
			END IF;
			
			IF vDefaultValue IS NOT NULL THEN
				SET @STMT = CONCAT(@STMT,' DEFAULT ', vDefaultValue);
			END IF;
			
			IF nCID < maxCID THEN
				SET @STMT = CONCAT(@STMT,',
');
			END IF;
		END IF;
		
		SET nCID = nCID + 1;
	END WHILE;
	
	IF CHAR_LENGTH(vPrimaryKeys) > 0 THEN
		SET @STMT = CONCAT(@STMT,',
	PRIMARY KEY (',vPrimaryKeys,')');
	END IF;
	
	SET @STMT = CONCAT(@STMT,'
) ENGINE=',vENGINE,' DEFAULT CHARSET=utf8;');
	
	SELECT @STMT AS `Sql`;
	
	-- PREPARE stmt FROM @STMT;
	-- EXECUTE stmt;
END$$

DELIMITER ;
