DROP TABLE IF EXISTS `dbv_table`;

CREATE TABLE `dbv_table` (
  `TID` INT NOT NULL AUTO_INCREMENT,
  `SchemaName` VARCHAR(192) DEFAULT NULL,
  `TableName` VARCHAR(192) DEFAULT NULL,
  `ENGINE` VARCHAR(192) DEFAULT NULL,
  `CREATE_OPTIONS` VARCHAR(765) DEFAULT NULL,
  `TABLE_COMMENT` VARCHAR(240) DEFAULT NULL,
  `PrimaryKeys` TEXT,
  PRIMARY KEY (`TID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;