DROP TABLE IF EXISTS `dbv_trigger`;

CREATE TABLE `dbv_trigger` (
  `TriID` INT NOT NULL AUTO_INCREMENT,
  `SchemaName` VARCHAR(64) NOT NULL DEFAULT '',
  `TriName` VARCHAR(64) NOT NULL DEFAULT '',
  `EVENT_MANIPULATION` VARCHAR(6) NOT NULL DEFAULT '',
  `TableName` VARCHAR(64) NOT NULL DEFAULT '',
  `ACTION_ORDER` BIGINT(4) NOT NULL DEFAULT '0',
  `ACTION_CONDITION` LONGTEXT,
  `ACTION_STATEMENT` LONGTEXT NOT NULL,
  `ACTION_ORIENTATION` VARCHAR(9) NOT NULL DEFAULT '',
  `ACTION_TIMING` VARCHAR(6) NOT NULL DEFAULT '',
  PRIMARY KEY (`TriID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;