DROP TABLE IF EXISTS `dbv_column`;

CREATE TABLE `dbv_column` (
  `CID` INT NOT NULL AUTO_INCREMENT,
  `TID` INT DEFAULT NULL,
  `ColName` VARCHAR(192) DEFAULT NULL,
  `DefaultValue` LONGTEXT,
  `NullAble` TINYINT DEFAULT NULL,
  `DATA_TYPE` VARCHAR(192) DEFAULT NULL,
  `CHARACTER_MAXIMUM_LENGTH` BIGINT DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` BIGINT DEFAULT NULL,
  `NUMERIC_PRECISION` BIGINT DEFAULT NULL,
  `NUMERIC_SCALE` BIGINT DEFAULT NULL,
  `CHARACTER_SET_NAME` VARCHAR(192) DEFAULT NULL,
  `COLLATION_NAME` VARCHAR(192) DEFAULT NULL,
  `COLUMN_TYPE` LONGTEXT,
  `COLUMN_KEY` VARCHAR(3) DEFAULT NULL,
  `is_auto_increment` TINYINT DEFAULT NULL,
  `COLUMN_COMMENT` VARCHAR(1024) DEFAULT NULL,
  `SchemaName` VARCHAR(192) DEFAULT NULL,
  `TableName` VARCHAR(192) DEFAULT NULL,
  PRIMARY KEY (`CID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;