DROP TABLE IF EXISTS `dbv_view`;

CREATE TABLE `dbv_view` (
  `VID` INT NOT NULL AUTO_INCREMENT,
  `SchemaName` VARCHAR(64) NOT NULL DEFAULT '',
  `TableName` VARCHAR(64) NOT NULL DEFAULT '',
  `VIEW_DEFINITION` LONGTEXT NOT NULL,
  PRIMARY KEY (`VID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;