CREATE TABLE IF NOT EXISTS `dbv_BuildLog` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `_InTime` DATETIME NOT NULL,
  `Type` INT NOT NULL DEFAULT 0,
  `Severity` INT NOT NULL DEFAULT 0,
  `Titile` VARCHAR(100) NOT NULL DEFAULT '',
  `Msg` LONGTEXT NOT NULL,
  AlarmGroupID INT NOT NULL DEFAULT 0,
  State INT NOT NULL DEFAULT 0,
  UNIQUE KEY `ID` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;