//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Apq_DBTools.EF
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class dbvEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“dbvEntities”部分中的连接字符串初始化新 dbvEntities 对象。
        /// </summary>
        public dbvEntities() : base("name=dbvEntities", "dbvEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 dbvEntities 对象。
        /// </summary>
        public dbvEntities(string connectionString) : base(connectionString, "dbvEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 dbvEntities 对象。
        /// </summary>
        public dbvEntities(EntityConnection connection) : base(connection, "dbvEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<dbv_column> dbv_column
        {
            get
            {
                if ((_dbv_column == null))
                {
                    _dbv_column = base.CreateObjectSet<dbv_column>("dbv_column");
                }
                return _dbv_column;
            }
        }
        private ObjectSet<dbv_column> _dbv_column;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<dbv_table> dbv_table
        {
            get
            {
                if ((_dbv_table == null))
                {
                    _dbv_table = base.CreateObjectSet<dbv_table>("dbv_table");
                }
                return _dbv_table;
            }
        }
        private ObjectSet<dbv_table> _dbv_table;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<dbv_proc> dbv_proc
        {
            get
            {
                if ((_dbv_proc == null))
                {
                    _dbv_proc = base.CreateObjectSet<dbv_proc>("dbv_proc");
                }
                return _dbv_proc;
            }
        }
        private ObjectSet<dbv_proc> _dbv_proc;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 dbv_column EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTodbv_column(dbv_column dbv_column)
        {
            base.AddObject("dbv_column", dbv_column);
        }
    
        /// <summary>
        /// 用于向 dbv_table EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTodbv_table(dbv_table dbv_table)
        {
            base.AddObject("dbv_table", dbv_table);
        }
    
        /// <summary>
        /// 用于向 dbv_proc EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTodbv_proc(dbv_proc dbv_proc)
        {
            base.AddObject("dbv_proc", dbv_proc);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbv", Name="dbv_column")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbv_column : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 dbv_column 对象。
        /// </summary>
        /// <param name="cID">CID 属性的初始值。</param>
        public static dbv_column Createdbv_column(global::System.Int32 cID)
        {
            dbv_column dbv_column = new dbv_column();
            dbv_column.CID = cID;
            return dbv_column;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Int32 _CID;
        partial void OnCIDChanging(global::System.Int32 value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchemaName
        {
            get
            {
                return _SchemaName;
            }
            set
            {
                OnSchemaNameChanging(value);
                ReportPropertyChanging("SchemaName");
                _SchemaName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchemaName");
                OnSchemaNameChanged();
            }
        }
        private global::System.String _SchemaName;
        partial void OnSchemaNameChanging(global::System.String value);
        partial void OnSchemaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColName
        {
            get
            {
                return _ColName;
            }
            set
            {
                OnColNameChanging(value);
                ReportPropertyChanging("ColName");
                _ColName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ColName");
                OnColNameChanged();
            }
        }
        private global::System.String _ColName;
        partial void OnColNameChanging(global::System.String value);
        partial void OnColNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] DefaultValue
        {
            get
            {
                return StructuralObject.GetValidValue(_DefaultValue);
            }
            set
            {
                OnDefaultValueChanging(value);
                ReportPropertyChanging("DefaultValue");
                _DefaultValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultValue");
                OnDefaultValueChanged();
            }
        }
        private global::System.Byte[] _DefaultValue;
        partial void OnDefaultValueChanging(global::System.Byte[] value);
        partial void OnDefaultValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> NullAble
        {
            get
            {
                return _NullAble;
            }
            set
            {
                OnNullAbleChanging(value);
                ReportPropertyChanging("NullAble");
                _NullAble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NullAble");
                OnNullAbleChanged();
            }
        }
        private Nullable<global::System.Boolean> _NullAble;
        partial void OnNullAbleChanging(Nullable<global::System.Boolean> value);
        partial void OnNullAbleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DATA_TYPE
        {
            get
            {
                return _DATA_TYPE;
            }
            set
            {
                OnDATA_TYPEChanging(value);
                ReportPropertyChanging("DATA_TYPE");
                _DATA_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DATA_TYPE");
                OnDATA_TYPEChanged();
            }
        }
        private global::System.String _DATA_TYPE;
        partial void OnDATA_TYPEChanging(global::System.String value);
        partial void OnDATA_TYPEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CHARACTER_MAXIMUM_LENGTH
        {
            get
            {
                return _CHARACTER_MAXIMUM_LENGTH;
            }
            set
            {
                OnCHARACTER_MAXIMUM_LENGTHChanging(value);
                ReportPropertyChanging("CHARACTER_MAXIMUM_LENGTH");
                _CHARACTER_MAXIMUM_LENGTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHARACTER_MAXIMUM_LENGTH");
                OnCHARACTER_MAXIMUM_LENGTHChanged();
            }
        }
        private Nullable<global::System.Int64> _CHARACTER_MAXIMUM_LENGTH;
        partial void OnCHARACTER_MAXIMUM_LENGTHChanging(Nullable<global::System.Int64> value);
        partial void OnCHARACTER_MAXIMUM_LENGTHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CHARACTER_OCTET_LENGTH
        {
            get
            {
                return _CHARACTER_OCTET_LENGTH;
            }
            set
            {
                OnCHARACTER_OCTET_LENGTHChanging(value);
                ReportPropertyChanging("CHARACTER_OCTET_LENGTH");
                _CHARACTER_OCTET_LENGTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHARACTER_OCTET_LENGTH");
                OnCHARACTER_OCTET_LENGTHChanged();
            }
        }
        private Nullable<global::System.Int64> _CHARACTER_OCTET_LENGTH;
        partial void OnCHARACTER_OCTET_LENGTHChanging(Nullable<global::System.Int64> value);
        partial void OnCHARACTER_OCTET_LENGTHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NUMERIC_PRECISION
        {
            get
            {
                return _NUMERIC_PRECISION;
            }
            set
            {
                OnNUMERIC_PRECISIONChanging(value);
                ReportPropertyChanging("NUMERIC_PRECISION");
                _NUMERIC_PRECISION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUMERIC_PRECISION");
                OnNUMERIC_PRECISIONChanged();
            }
        }
        private Nullable<global::System.Int64> _NUMERIC_PRECISION;
        partial void OnNUMERIC_PRECISIONChanging(Nullable<global::System.Int64> value);
        partial void OnNUMERIC_PRECISIONChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NUMERIC_SCALE
        {
            get
            {
                return _NUMERIC_SCALE;
            }
            set
            {
                OnNUMERIC_SCALEChanging(value);
                ReportPropertyChanging("NUMERIC_SCALE");
                _NUMERIC_SCALE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUMERIC_SCALE");
                OnNUMERIC_SCALEChanged();
            }
        }
        private Nullable<global::System.Int64> _NUMERIC_SCALE;
        partial void OnNUMERIC_SCALEChanging(Nullable<global::System.Int64> value);
        partial void OnNUMERIC_SCALEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHARACTER_SET_NAME
        {
            get
            {
                return _CHARACTER_SET_NAME;
            }
            set
            {
                OnCHARACTER_SET_NAMEChanging(value);
                ReportPropertyChanging("CHARACTER_SET_NAME");
                _CHARACTER_SET_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHARACTER_SET_NAME");
                OnCHARACTER_SET_NAMEChanged();
            }
        }
        private global::System.String _CHARACTER_SET_NAME;
        partial void OnCHARACTER_SET_NAMEChanging(global::System.String value);
        partial void OnCHARACTER_SET_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COLLATION_NAME
        {
            get
            {
                return _COLLATION_NAME;
            }
            set
            {
                OnCOLLATION_NAMEChanging(value);
                ReportPropertyChanging("COLLATION_NAME");
                _COLLATION_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COLLATION_NAME");
                OnCOLLATION_NAMEChanged();
            }
        }
        private global::System.String _COLLATION_NAME;
        partial void OnCOLLATION_NAMEChanging(global::System.String value);
        partial void OnCOLLATION_NAMEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] COLUMN_TYPE
        {
            get
            {
                return StructuralObject.GetValidValue(_COLUMN_TYPE);
            }
            set
            {
                OnCOLUMN_TYPEChanging(value);
                ReportPropertyChanging("COLUMN_TYPE");
                _COLUMN_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COLUMN_TYPE");
                OnCOLUMN_TYPEChanged();
            }
        }
        private global::System.Byte[] _COLUMN_TYPE;
        partial void OnCOLUMN_TYPEChanging(global::System.Byte[] value);
        partial void OnCOLUMN_TYPEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_auto_increment
        {
            get
            {
                return _is_auto_increment;
            }
            set
            {
                Onis_auto_incrementChanging(value);
                ReportPropertyChanging("is_auto_increment");
                _is_auto_increment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_auto_increment");
                Onis_auto_incrementChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_auto_increment;
        partial void Onis_auto_incrementChanging(Nullable<global::System.Boolean> value);
        partial void Onis_auto_incrementChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COLUMN_COMMENT
        {
            get
            {
                return _COLUMN_COMMENT;
            }
            set
            {
                OnCOLUMN_COMMENTChanging(value);
                ReportPropertyChanging("COLUMN_COMMENT");
                _COLUMN_COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COLUMN_COMMENT");
                OnCOLUMN_COMMENTChanged();
            }
        }
        private global::System.String _COLUMN_COMMENT;
        partial void OnCOLUMN_COMMENTChanging(global::System.String value);
        partial void OnCOLUMN_COMMENTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TID
        {
            get
            {
                return _TID;
            }
            set
            {
                OnTIDChanging(value);
                ReportPropertyChanging("TID");
                _TID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TID");
                OnTIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TID;
        partial void OnTIDChanging(Nullable<global::System.Int32> value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COLUMN_KEY
        {
            get
            {
                return _COLUMN_KEY;
            }
            set
            {
                OnCOLUMN_KEYChanging(value);
                ReportPropertyChanging("COLUMN_KEY");
                _COLUMN_KEY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COLUMN_KEY");
                OnCOLUMN_KEYChanged();
            }
        }
        private global::System.String _COLUMN_KEY;
        partial void OnCOLUMN_KEYChanging(global::System.String value);
        partial void OnCOLUMN_KEYChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbv", Name="dbv_proc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbv_proc : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 dbv_proc 对象。
        /// </summary>
        /// <param name="pID">PID 属性的初始值。</param>
        public static dbv_proc Createdbv_proc(global::System.Int32 pID)
        {
            dbv_proc dbv_proc = new dbv_proc();
            dbv_proc.PID = pID;
            return dbv_proc;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PID
        {
            get
            {
                return _PID;
            }
            set
            {
                if (_PID != value)
                {
                    OnPIDChanging(value);
                    ReportPropertyChanging("PID");
                    _PID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PID");
                    OnPIDChanged();
                }
            }
        }
        private global::System.Int32 _PID;
        partial void OnPIDChanging(global::System.Int32 value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchemaName
        {
            get
            {
                return _SchemaName;
            }
            set
            {
                OnSchemaNameChanging(value);
                ReportPropertyChanging("SchemaName");
                _SchemaName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchemaName");
                OnSchemaNameChanged();
            }
        }
        private global::System.String _SchemaName;
        partial void OnSchemaNameChanging(global::System.String value);
        partial void OnSchemaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcName
        {
            get
            {
                return _ProcName;
            }
            set
            {
                OnProcNameChanging(value);
                ReportPropertyChanging("ProcName");
                _ProcName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcName");
                OnProcNameChanged();
            }
        }
        private global::System.String _ProcName;
        partial void OnProcNameChanging(global::System.String value);
        partial void OnProcNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String param_list
        {
            get
            {
                return _param_list;
            }
            set
            {
                Onparam_listChanging(value);
                ReportPropertyChanging("param_list");
                _param_list = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("param_list");
                Onparam_listChanged();
            }
        }
        private global::System.String _param_list;
        partial void Onparam_listChanging(global::System.String value);
        partial void Onparam_listChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String returns
        {
            get
            {
                return _returns;
            }
            set
            {
                OnreturnsChanging(value);
                ReportPropertyChanging("returns");
                _returns = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("returns");
                OnreturnsChanged();
            }
        }
        private global::System.String _returns;
        partial void OnreturnsChanging(global::System.String value);
        partial void OnreturnsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbv", Name="dbv_table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbv_table : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 dbv_table 对象。
        /// </summary>
        /// <param name="tID">TID 属性的初始值。</param>
        public static dbv_table Createdbv_table(global::System.Int32 tID)
        {
            dbv_table dbv_table = new dbv_table();
            dbv_table.TID = tID;
            return dbv_table;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.Int32 _TID;
        partial void OnTIDChanging(global::System.Int32 value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchemaName
        {
            get
            {
                return _SchemaName;
            }
            set
            {
                OnSchemaNameChanging(value);
                ReportPropertyChanging("SchemaName");
                _SchemaName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchemaName");
                OnSchemaNameChanged();
            }
        }
        private global::System.String _SchemaName;
        partial void OnSchemaNameChanging(global::System.String value);
        partial void OnSchemaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENGINE
        {
            get
            {
                return _ENGINE;
            }
            set
            {
                OnENGINEChanging(value);
                ReportPropertyChanging("ENGINE");
                _ENGINE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENGINE");
                OnENGINEChanged();
            }
        }
        private global::System.String _ENGINE;
        partial void OnENGINEChanging(global::System.String value);
        partial void OnENGINEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CREATE_OPTIONS
        {
            get
            {
                return _CREATE_OPTIONS;
            }
            set
            {
                OnCREATE_OPTIONSChanging(value);
                ReportPropertyChanging("CREATE_OPTIONS");
                _CREATE_OPTIONS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CREATE_OPTIONS");
                OnCREATE_OPTIONSChanged();
            }
        }
        private global::System.String _CREATE_OPTIONS;
        partial void OnCREATE_OPTIONSChanging(global::System.String value);
        partial void OnCREATE_OPTIONSChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TABLE_COMMENT
        {
            get
            {
                return _TABLE_COMMENT;
            }
            set
            {
                OnTABLE_COMMENTChanging(value);
                ReportPropertyChanging("TABLE_COMMENT");
                _TABLE_COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TABLE_COMMENT");
                OnTABLE_COMMENTChanged();
            }
        }
        private global::System.String _TABLE_COMMENT;
        partial void OnTABLE_COMMENTChanging(global::System.String value);
        partial void OnTABLE_COMMENTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimaryKeys
        {
            get
            {
                return _PrimaryKeys;
            }
            set
            {
                OnPrimaryKeysChanging(value);
                ReportPropertyChanging("PrimaryKeys");
                _PrimaryKeys = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimaryKeys");
                OnPrimaryKeysChanged();
            }
        }
        private global::System.String _PrimaryKeys;
        partial void OnPrimaryKeysChanging(global::System.String value);
        partial void OnPrimaryKeysChanged();

        #endregion
    
    }

    #endregion
    
}
