
-- 统计信息
--ALTER DATABASE DBName SET AUTO_CREATE_STATISTICS ON WITH ROLLBACK IMMEDIATE;	-- 自动创建
--ALTER DATABASE DBName SET AUTO_UPDATE_STATISTICS ON WITH NO_WAIT;	-- 自动更新
ALTER DATABASE DBName SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH ROLLBACK IMMEDIATE; -- 自动更新为异步方式(要求打开上一个选项)

-- 行版本
ALTER DATABASE DBName SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE -- 需要单连接,因此在迁移/维护时才能做
ALTER DATABASE DBName SET ALLOW_SNAPSHOT_ISOLATION ON	-- 快照隔离级别
SELECT */*is_read_committed_snapshot_on*/ FROM sys.databases -- 查看当前设置

-- 自动收缩
ALTER DATABASE DBName SET AUTO_SHRINK ON WITH ROLLBACK IMMEDIATE WITH NO_WAIT	-- 一般不设置该项

-- 单用户
ALTER DATABASE DBName SET SINGLE_USER WITH ROLLBACK IMMEDIATE
