
-- 行版本
ALTER DATABASE <DBName> SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE -- 需要单连接,因此在迁移/维护时才能做
ALTER DATABASE <DBName> SET ALLOW_SNAPSHOT_ISOLATION ON	-- 快照隔离级别

-- 自动创建统计信息
ALTER DATABASE <DBName> SET AUTO_CREATE_STATISTICS ON WITH ROLLBACK IMMEDIATE

-- 一般不设置这两项
ALTER DATABASE <DBName> SET AUTO_SHRINK ON WITH ROLLBACK IMMEDIATE	-- 自动收缩
ALTER DATABASE <DBName> SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH ROLLBACK IMMEDIATE -- 自动更新统计信息

-- 单用户
ALTER DATABASE <DBName> SET SINGLE_USER WITH ROLLBACK IMMEDIATE
 