 USE [master]
GO

/****** Object:  Database [Apq_DBA]    Script Date: 10/11/2010 17:45:56 ******/
CREATE DATABASE [Apq_DBA] ON  PRIMARY 
( NAME = N'Apq_DBA', FILENAME = N'D:\DB\Apq_DBA\Apq_DBA.mdf' , SIZE = 3968KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Apq_DBA_log', FILENAME = N'D:\DB\Apq_DBA\Apq_DBA_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

-- 启用行版本控制 ---------------------------------------------------------------------------------- 
USE [Apq_DBA]
GO
ALTER DATABASE Apq_DBA SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE -- 需要单连接,因此在迁移/维护时才能做
GO
-- =================================================================================================

ALTER DATABASE [Apq_DBA] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Apq_DBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Apq_DBA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Apq_DBA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Apq_DBA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Apq_DBA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Apq_DBA] SET ARITHABORT OFF 
GO

ALTER DATABASE [Apq_DBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Apq_DBA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Apq_DBA] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Apq_DBA] SET AUTO_UPDATE_STATISTICS OFF 
GO

ALTER DATABASE [Apq_DBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Apq_DBA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Apq_DBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Apq_DBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Apq_DBA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Apq_DBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Apq_DBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Apq_DBA] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [Apq_DBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Apq_DBA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Apq_DBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Apq_DBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Apq_DBA] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Apq_DBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Apq_DBA] SET  READ_WRITE 
GO

ALTER DATABASE [Apq_DBA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Apq_DBA] SET  MULTI_USER 
GO

ALTER DATABASE [Apq_DBA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Apq_DBA] SET DB_CHAINING OFF 
GO
