//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3607
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace pdbp.WS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginSoap", Namespace="http://tempuri.org/")]
    public partial class Login : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApqUser_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback dtxc_Reg_UserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS_RegOperationCompleted;
        
        private System.Threading.SendOrPostCallback Login_LoginNameFromCookieOperationCompleted;
        
        private System.Threading.SendOrPostCallback Login_LoginNameOperationCompleted;
        
        /// <remarks/>
        public Login() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["WS_Login"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/pdbp/pdbp.WS/Login.asmx";
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ApqUser_LoginCompletedEventHandler ApqUser_LoginCompleted;
        
        /// <remarks/>
        public event dtxc_Reg_UserNameCompletedEventHandler dtxc_Reg_UserNameCompleted;
        
        /// <remarks/>
        public event WS_RegCompletedEventHandler WS_RegCompleted;
        
        /// <remarks/>
        public event Login_LoginNameFromCookieCompletedEventHandler Login_LoginNameFromCookieCompleted;
        
        /// <remarks/>
        public event Login_LoginNameCompletedEventHandler Login_LoginNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApqUser_Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STReturn ApqUser_Login(int UserSrc, string UserName) {
            object[] results = this.Invoke("ApqUser_Login", new object[] {
                        UserSrc,
                        UserName});
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginApqUser_Login(int UserSrc, string UserName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ApqUser_Login", new object[] {
                        UserSrc,
                        UserName}, callback, asyncState);
        }
        
        /// <remarks/>
        public STReturn EndApqUser_Login(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public void ApqUser_LoginAsync(int UserSrc, string UserName) {
            this.ApqUser_LoginAsync(UserSrc, UserName, null);
        }
        
        /// <remarks/>
        public void ApqUser_LoginAsync(int UserSrc, string UserName, object userState) {
            if ((this.ApqUser_LoginOperationCompleted == null)) {
                this.ApqUser_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApqUser_LoginOperationCompleted);
            }
            this.InvokeAsync("ApqUser_Login", new object[] {
                        UserSrc,
                        UserName}, this.ApqUser_LoginOperationCompleted, userState);
        }
        
        private void OnApqUser_LoginOperationCompleted(object arg) {
            if ((this.ApqUser_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApqUser_LoginCompleted(this, new ApqUser_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtxc_Reg_UserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STReturn dtxc_Reg_UserName(string UserName, string LoginName, string LoginPwd, short Sex, string PhotoUrl, long IntroUserID, string Alipay, int UserType, System.DateTime Birthday, string IDCard, string IDCard_Name, short IDCard_Sex, string IDCard_PhotoUrl) {
            object[] results = this.Invoke("dtxc_Reg_UserName", new object[] {
                        UserName,
                        LoginName,
                        LoginPwd,
                        Sex,
                        PhotoUrl,
                        IntroUserID,
                        Alipay,
                        UserType,
                        Birthday,
                        IDCard,
                        IDCard_Name,
                        IDCard_Sex,
                        IDCard_PhotoUrl});
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindtxc_Reg_UserName(string UserName, string LoginName, string LoginPwd, short Sex, string PhotoUrl, long IntroUserID, string Alipay, int UserType, System.DateTime Birthday, string IDCard, string IDCard_Name, short IDCard_Sex, string IDCard_PhotoUrl, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dtxc_Reg_UserName", new object[] {
                        UserName,
                        LoginName,
                        LoginPwd,
                        Sex,
                        PhotoUrl,
                        IntroUserID,
                        Alipay,
                        UserType,
                        Birthday,
                        IDCard,
                        IDCard_Name,
                        IDCard_Sex,
                        IDCard_PhotoUrl}, callback, asyncState);
        }
        
        /// <remarks/>
        public STReturn Enddtxc_Reg_UserName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public void dtxc_Reg_UserNameAsync(string UserName, string LoginName, string LoginPwd, short Sex, string PhotoUrl, long IntroUserID, string Alipay, int UserType, System.DateTime Birthday, string IDCard, string IDCard_Name, short IDCard_Sex, string IDCard_PhotoUrl) {
            this.dtxc_Reg_UserNameAsync(UserName, LoginName, LoginPwd, Sex, PhotoUrl, IntroUserID, Alipay, UserType, Birthday, IDCard, IDCard_Name, IDCard_Sex, IDCard_PhotoUrl, null);
        }
        
        /// <remarks/>
        public void dtxc_Reg_UserNameAsync(string UserName, string LoginName, string LoginPwd, short Sex, string PhotoUrl, long IntroUserID, string Alipay, int UserType, System.DateTime Birthday, string IDCard, string IDCard_Name, short IDCard_Sex, string IDCard_PhotoUrl, object userState) {
            if ((this.dtxc_Reg_UserNameOperationCompleted == null)) {
                this.dtxc_Reg_UserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondtxc_Reg_UserNameOperationCompleted);
            }
            this.InvokeAsync("dtxc_Reg_UserName", new object[] {
                        UserName,
                        LoginName,
                        LoginPwd,
                        Sex,
                        PhotoUrl,
                        IntroUserID,
                        Alipay,
                        UserType,
                        Birthday,
                        IDCard,
                        IDCard_Name,
                        IDCard_Sex,
                        IDCard_PhotoUrl}, this.dtxc_Reg_UserNameOperationCompleted, userState);
        }
        
        private void Ondtxc_Reg_UserNameOperationCompleted(object arg) {
            if ((this.dtxc_Reg_UserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dtxc_Reg_UserNameCompleted(this, new dtxc_Reg_UserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS_Reg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STReturn WS_Reg(string LoginName, string LoginPwd, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Ipa, string Introducer) {
            object[] results = this.Invoke("WS_Reg", new object[] {
                        LoginName,
                        LoginPwd,
                        Ipa,
                        Introducer});
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWS_Reg(string LoginName, string LoginPwd, byte[] Ipa, string Introducer, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WS_Reg", new object[] {
                        LoginName,
                        LoginPwd,
                        Ipa,
                        Introducer}, callback, asyncState);
        }
        
        /// <remarks/>
        public STReturn EndWS_Reg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public void WS_RegAsync(string LoginName, string LoginPwd, byte[] Ipa, string Introducer) {
            this.WS_RegAsync(LoginName, LoginPwd, Ipa, Introducer, null);
        }
        
        /// <remarks/>
        public void WS_RegAsync(string LoginName, string LoginPwd, byte[] Ipa, string Introducer, object userState) {
            if ((this.WS_RegOperationCompleted == null)) {
                this.WS_RegOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS_RegOperationCompleted);
            }
            this.InvokeAsync("WS_Reg", new object[] {
                        LoginName,
                        LoginPwd,
                        Ipa,
                        Introducer}, this.WS_RegOperationCompleted, userState);
        }
        
        private void OnWS_RegOperationCompleted(object arg) {
            if ((this.WS_RegCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS_RegCompleted(this, new WS_RegCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login_LoginNameFromCookie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STReturn Login_LoginNameFromCookie(string LoginName, string CryptLoginPwd) {
            object[] results = this.Invoke("Login_LoginNameFromCookie", new object[] {
                        LoginName,
                        CryptLoginPwd});
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin_LoginNameFromCookie(string LoginName, string CryptLoginPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login_LoginNameFromCookie", new object[] {
                        LoginName,
                        CryptLoginPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public STReturn EndLogin_LoginNameFromCookie(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public void Login_LoginNameFromCookieAsync(string LoginName, string CryptLoginPwd) {
            this.Login_LoginNameFromCookieAsync(LoginName, CryptLoginPwd, null);
        }
        
        /// <remarks/>
        public void Login_LoginNameFromCookieAsync(string LoginName, string CryptLoginPwd, object userState) {
            if ((this.Login_LoginNameFromCookieOperationCompleted == null)) {
                this.Login_LoginNameFromCookieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogin_LoginNameFromCookieOperationCompleted);
            }
            this.InvokeAsync("Login_LoginNameFromCookie", new object[] {
                        LoginName,
                        CryptLoginPwd}, this.Login_LoginNameFromCookieOperationCompleted, userState);
        }
        
        private void OnLogin_LoginNameFromCookieOperationCompleted(object arg) {
            if ((this.Login_LoginNameFromCookieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Login_LoginNameFromCookieCompleted(this, new Login_LoginNameFromCookieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login_LoginName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STReturn Login_LoginName(string LoginName, string LoginPwd) {
            object[] results = this.Invoke("Login_LoginName", new object[] {
                        LoginName,
                        LoginPwd});
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin_LoginName(string LoginName, string LoginPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login_LoginName", new object[] {
                        LoginName,
                        LoginPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public STReturn EndLogin_LoginName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((STReturn)(results[0]));
        }
        
        /// <remarks/>
        public void Login_LoginNameAsync(string LoginName, string LoginPwd) {
            this.Login_LoginNameAsync(LoginName, LoginPwd, null);
        }
        
        /// <remarks/>
        public void Login_LoginNameAsync(string LoginName, string LoginPwd, object userState) {
            if ((this.Login_LoginNameOperationCompleted == null)) {
                this.Login_LoginNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogin_LoginNameOperationCompleted);
            }
            this.InvokeAsync("Login_LoginName", new object[] {
                        LoginName,
                        LoginPwd}, this.Login_LoginNameOperationCompleted, userState);
        }
        
        private void OnLogin_LoginNameOperationCompleted(object arg) {
            if ((this.Login_LoginNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Login_LoginNameCompleted(this, new Login_LoginNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class STReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nReturnField;
        
        private string exMsgField;
        
        private object fNReturnField;
        
        private object[] pOutsField;
        
        /// <remarks/>
        public int NReturn {
            get {
                return this.nReturnField;
            }
            set {
                this.nReturnField = value;
                this.RaisePropertyChanged("NReturn");
            }
        }
        
        /// <remarks/>
        public string ExMsg {
            get {
                return this.exMsgField;
            }
            set {
                this.exMsgField = value;
                this.RaisePropertyChanged("ExMsg");
            }
        }
        
        /// <remarks/>
        public object FNReturn {
            get {
                return this.fNReturnField;
            }
            set {
                this.fNReturnField = value;
                this.RaisePropertyChanged("FNReturn");
            }
        }
        
        /// <remarks/>
        public object[] POuts {
            get {
                return this.pOutsField;
            }
            set {
                this.pOutsField = value;
                this.RaisePropertyChanged("POuts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ApqUser_LoginCompletedEventHandler(object sender, ApqUser_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApqUser_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApqUser_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public STReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((STReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void dtxc_Reg_UserNameCompletedEventHandler(object sender, dtxc_Reg_UserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dtxc_Reg_UserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dtxc_Reg_UserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public STReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((STReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void WS_RegCompletedEventHandler(object sender, WS_RegCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS_RegCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS_RegCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public STReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((STReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void Login_LoginNameFromCookieCompletedEventHandler(object sender, Login_LoginNameFromCookieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Login_LoginNameFromCookieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Login_LoginNameFromCookieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public STReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((STReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void Login_LoginNameCompletedEventHandler(object sender, Login_LoginNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Login_LoginNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Login_LoginNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public STReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((STReturn)(this.results[0]));
            }
        }
    }
}
